### ISSUE TITLE
DiscordAPIError: cannot send empty message

### ISSUE THREAD

**Issue by 41LL0N** [RemyK888/discord-music-system#1]
Hi,

Everytime I run one of the commands that is in the npm package, it sends nothing.

No embeds, no messages can keeps throwing a DiscordAPIError.

The only command that works is the play command, but sends no messages.

Can I please get some help with this?

**Comment by kisiel23** [comment]
Did you install all dependencies?

**Comment by 41LL0N** [comment]
> Did you install all dependencies?

All dependencies should install on their own, if they're from NPM.
