### ISSUE TITLE
Bot leaves vc

### ISSUE THREAD

**Issue by DentyMods** [RemyK888/discord-music-system#11]
bot just joins VC when it says that its playing music and just leaves doing nothing,

**Comment by DentyMods** [comment]
now its saying The music player has been destroyed!

**Comment by imconfusionn** [comment]
Hey sad to hear that its not working.

Do you have eny errors in you console?

**Comment by PasinduDushan** [comment]
I got that too

**Comment by PasinduDushan** [comment]
But no errors

**Comment by PasinduDushan** [comment]
I got it. You have to install all the dependencies included in the npm package. https://www.npmjs.com/package/discord-music-system?activeTab=dependencies

**Comment by imconfusionn** [comment]
Thats really weird. It shude automatically install tho's when you download the npm pack. If some one else has this issue i would recomend deleting the pack and reinstalling it

**Comment by PasinduDushan** [comment]
I tried it several times.

**Comment by DentyMods** [comment]
yea no errors, also that fixed it so thanks
