### ISSUE TITLE
Music player destroys itself after playing "Polish cow instrumental"

### ISSUE THREAD

**Issue by cheslin23t** [RemyK888/discord-music-system#12]
[2021-04-28 16-23-15.zip](https://github.com/RemyK888/discord-music-system/files/6394608/2021-04-28.16-23-15.zip)

**Comment by Nailed-it1** [comment]
This issue should to be fixed in the next update of the music system

**Comment by RemyK888** [comment]
Update this week or next week

**Comment by RemyK888** [comment]
Hey new version is available, download it using `npm install discord-music-system@latest` !
If you don't have any question or problems can I close this issue ?
