### ISSUE TITLE
Bot No longer working for discord.js v13

### ISSUE THREAD

**Issue by sivelswhy** [RemyK888/discord-music-system#16]
The bot is now no longer working with discord.js v12

**Comment by Scarner56** [comment]
This package does not work with discord.js v13

**Comment by sivelswhy** [comment]
v12 or whatever it user but you get bunch of errors

**Comment by retrouser955** [comment]
yes it does not. maybe try using discord-player or discord-music-player

**Comment by Scarner56** [comment]
> v12 or whatever it user but you get bunch of errors

yep remyK didnt fix this package

**Comment by retrouser955** [comment]
guys try using discord-player or discord-music-player. (ie im getting ignored)

**Comment by RemyK888** [comment]
Hello, this package is designed for version 12, so it will not work with version 13.
For several reasons, including functionality, I will not update this project for version 13, perhaps a later version.

However I can offer to create an open source and royalty free music bot code using version 13.

For more information, join my Discord server, we will be more comfortable to talk there: https://discord.gg/Mm6CKUr6Y3

~ RemyK
