### ISSUE TITLE
Recent errors when using music commands

### ISSUE THREAD

**Issue by ChrisTVH** [RemyK888/discord-music-system#3]
This time I am using the latest version after using the music commands for a little while, these errors appear that I will leave in this compressed file with the log
[log.zip](https://github.com/RemyK888/discord-music-system/files/5505635/log.zip)

**Comment by RemyK888** [comment]
Hey @ChrisTVH, this error is from `ytdl-core`, the package used in mine to find YouTube videos. So I can't really help you, try to ask the ytdl-core's developers.

**Comment by ChrisTVH** [comment]
But the problem is that the discord music system package uses these dependencies

**Comment by RemyK888** [comment]
Hmm i must use ytdl core
