### ISSUE TITLE
Music dont add to queue

### ISSUE THREAD

**Issue by DeathMario** [RemyK888/discord-music-system#4]
The system doesnt add the music to the queue when i add more songs, it says the player has been created again and stops the music and starts the other

**Comment by RemyK888** [comment]
Hey @DeathMario, which version of `discord-music-system` do you use ? You can check it in the package.json.

**Comment by DeathMario** [comment]
Lastest

**Comment by DeathMario** [comment]
3.2.1

**Comment by RemyK888** [comment]
This error i strange, try to update all your packages.

**Comment by DeathMario** [comment]
Hmmm npm install?

**Comment by RemyK888** [comment]
Yes use `npm install`

**Comment by DeathMario** [comment]
let me send a pic

**Comment by DeathMario** [comment]
![Uploading Screenshot_20201108-110741.png…]()

**Comment by RemyK888** [comment]
Maybe that you can join my discord server to speak easily ? https://discord.gg/yWpCSAwk

**Comment by DeathMario** [comment]
![Screenshot_20201108-110741](https://user-images.githubusercontent.com/69960734/98463541-b71e2200-21b3-11eb-8c2e-21d2807f8191.png)

**Comment by DeathMario** [comment]
> Maybe that you can join my discord server to speak easily ? https://discord.gg/yWpCSAwk

Im Pandita en halloween
let me join
