### ISSUE TITLE
Music coammnds output does load

### ISSUE THREAD

**Issue by MaximKing1** [RemyK888/discord-music-system#5]
When I do $play it will send 3 messages saying it’s not in VC when I’m in the Voice Channel it will play but will spam chat and don’t stop at all and $stop don’t work.!

**Comment by MaximKing1** [comment]
@RemyK888

**Comment by RemyK888** [comment]
Send and explain the error.

**Comment by MaximKing1** [comment]
Well I get no errors in the log it will play but on the Console when bot is started it will spam
`------- Discord Music System -------
> Version: 3.2.1
> State: Loaded
------------- Music Bot ------------
NEW:  Custom language translation: edit the language.json in the language folder!` that every 10 seconds and when using $play (song) it will play it but will spam the chat with the embed sayings it’s been created and only way to stop it was to restart the bot. Also the $add command didn’t work and $list just says you didn’t say a song? @RemyK888

**Comment by RemyK888** [comment]
Send your index code.
I think that you have a bad usage of `onMessage()` function.

**Comment by MaximKing1** [comment]
@RemyK888 
`            const bot = new MusicBot({
    botPrefix: prefix, // Example: !
 ytApiKey: 'myAPIToken', // Video to explain how to get it: https://www.youtube.com/watch?v=VqML5F8hcRQ
    botClient: client // Your Discord client. Here we're using discord.js so it's the Discord.Client()
});

client.on('message', message => { 
    if(message.content.startsWith(bot.prefix)) { 
        bot.onMessage(message); 
    };
});`

**Comment by RemyK888** [comment]
send the whole code
